### ISSUE TITLE
Cannot run with only example data on Raspberry Pi 3

### ISSUE THREAD

**Issue by razgr1z912** [flyonspeed/TronView#44]
I have set it up using the instructions in TronView/docs/rpi_setup.md. 

I have two issues that prevent me from running the application with the example data. When I run the main.py file, the screen shows the example display correctly, but it is a static image as the python file hits an exception and does not continue to run.

**(1) During setup.sh, when trying to install python-pygame and python-serial, they are not available. See below:**

```
Errors installing python-pygame and python-serial:
pi@raspberrypi:~/efis_to_hud $ util/rpi/setup.sh
Setup Pi for running HUD software? (y or n)
 y
Enabling serial port
disable splash image
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python-pygame is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package python-serial is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-serial' has no installation candidate
E: Package 'python-pygame' has no installation candidate
E: Unable to locate package python-pyaudio
```
**(2) When trying to run main.py with example data, I get an exception in Thread-1.**
```
pi@raspberrypi:~/efis_to_hud $ sudo python main.py -i serial_d100 -e
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Creating DataRecorder dir: /flightlog/
armv7l
Running on RaspberryPi
Input data module 0: serial_d100
armv7l
Opening Logfile: lib/inputs/_example_data/dynon_d100_data1.txt
speed distance format: mph 
temperature format: C 
Loading screen module: Default
pygame-menu 4.3.6
No protocol specified
No protocol specified
sys.platform:linux
platform.machine:armv7l
default to XDisplay :10.0
Init Screen: Default 1920x1080
Init Mod: ArtificalHorz 1920x1080
Init Mod: Horizon 1920x1080
HUD x degree_per_pixel: 0.006771
Init Mod: HUD AOA 120x1070
Init Mod: Slip Skid 250x50
Init Mod: Menu 400x300
Init Mod: Traffic Scope 400x400
SmartDisplay drawable offset: 0,0 to 1920,1080
SmartDisplay New screen width/height: 1920,1080
SmartDisplay center x/y: 960,540
SmartDisplay real center x/y: 960,540
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/pi/efis_to_hud/main.py", line 52, in run
    shared.aircraft = shared.CurrentInput.readMessage(shared.aircraft)
  File "/home/pi/efis_to_hud/lib/inputs/serial_d100.py", line 108, in readMessage
    self.ser.flushInput()  # flush the serial after every message else we see delays
AttributeError: '_io.TextIOWrapper' object has no attribute 'flushInput'
```

This was all being done on a fresh install of Raspberry Pi OS (32 bit), kernel 5.15, debian version 11.

Any help would be great! I would love to get this up and running to pull EFIS and EMS data from my Dynon D100 series device in real time.

**Comment by dinglewanker** [comment]
hey @razgr1z912 looks like the setup.sh script is using apt-get to install those python packages.  And maybe they are no longer in the apt-get repos.

You might try installing those packages using pip3?  try running these from the command line.

```
sudo pip3 install pyserial
sudo pip3 install pygame
sudo pip3 install pyaudio

```
Also not sure if the script stopping after failing, but after that it trys to install a few more things.

```
sudo pip3 install pygame_menu
sudo pip3 install geographiclib
sudo apt install libsdl2-ttf-2.0-0
```

**Comment by dinglewanker** [comment]
@razgr1z912 hmmmm... pyserial may be the wrong package..  if that doesn't work try removing that package and running.

sudo pip3 install serial

**Comment by dinglewanker** [comment]
@razgr1z912 ok.  Looks like its the wrong python serial library.  It's trying to use flushInput() method but that isn't found.  

Looking around I see 
[https://pyserial.readthedocs.io/en/latest/pyserial_api.html](url)

Looks like they renamed the method.
`
reset_input_buffer()
Changed in version 3.0: renamed from flushInput()
`

Looks like you are using a different version of the python library?  Probably a newer better one then we are using because I haven't tried installing it in a while :)

Do you know how to branch and create a Pull Request in GitHub?  If you want to update the code and submit it.

**Comment by razgr1z912** [comment]
It still is throwing an error with reset_input_buffer() instead of the depricated flushInput().

Interestingly, the G3X example works perfectly and has that flushInput() line commented out. I commented out both times that was being called and now the example seems to work. I am not sure if it will affect the accuracy of the serial data or not, but it seems to be working with just those two lines commented out. I have not used GitHub much but if that is an acceptable solution, I can try to update that file.

**Comment by dinglewanker** [comment]
ok.  I'll have to look into that more.  We may not need the flush input methods anymore.

**Comment by hpmicrowave** [comment]
I need to commit the updates I’ve been working on that are good to go.  I’ve added a extra item to the Config file that allows you to adjust the waterline up and down electro match the aircraft boresight when the plane is level and also added the gun funnel for 25,30,& 35 ft wingspans. Right now I’m working on the gun director function with ADSB tgt ranging. Sent from my iPhoneOn Feb 17, 2023, at 5:19 PM, dinglewanker ***@***.***> wrote:﻿
ok.  I'll have to look into that more.  We may not need the flush input methods anymore.

**Comment by brightproject** [comment]
I'm running the script on a PC in Windows 10.
For me, command:
python3 main.py -i serial_d100 -e
Gives next result:
```
pygame 2.5.2 (SDL 2.28.3, Python 3.11.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
AMD64
Input data module 0: serial_d100
AMD64
Opening Logfile: lib/inputs/_example_data/dynon_d100_data1.txt
speed distance format: mph
temperature format: C
Loading screen module: Default
pygame-menu 4.4.3
sys.platform:win32
platform.machine:AMD64
Init Screen: Default 2560x1440
Init Mod: ArtificalHorz 2560x1440
Init Mod: Horizon 2560x1440
HUD x degree_per_pixel: 0.005078
Init Mod: HUD AOA 120x1430
Init Mod: Slip Skid 250x50
Init Mod: Menu 400x300
Init Mod: Traffic Scope 400x400
SmartDisplay drawable offset: 0,0 to 2560,1440
SmartDisplay New screen width/height: 2560,1440
SmartDisplay center x/y: 1280,720
SmartDisplay real center x/y: 1280,720
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "G:\Need_info\Проекты\Авионика\HUD_SynteticVision\TronView_HUD\main.py", line 52, in run
    shared.aircraft = shared.CurrentInput.readMessage(shared.aircraft)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Need_info\Проекты\Авионика\HUD_SynteticVision\TronView_HUD\lib\inputs\serial_d100.py", line 108, in readMessage
    self.ser.flushInput()  # flush the serial after every message else we see delays
    ^^^^^^^^^^^^^^^^^^^
AttributeError: '_io.TextIOWrapper' object has no attribute 'flushInput'
```
The image appears in full screen.
![Start_yes_no](https://github.com/flyonspeed/TronView/assets/1788098/9a821ef9-64d6-4702-ab8c-029c2865f96e)
As far as I understand, I'm running DEMO mode and it should take data from the file and display it on the screen, but it doesn't.
